SCROLL_PAUSE_TIME = 2
LINK = "https://towardsdatascience.com/"
ARTICLE_CLASS = 'postMetaInline postMetaInline-authorLockup ui-captionStrong u-flex1 u-noWrapWithEllipsis'
TITLE_CLASS = 'u-letterSpacingTight u-lineHeightTighter u-breakWord u-textOverflowEllipsis u-lineClamp3 u-fontSize24'
SUB_TITLE_CLASS = 'u-fontSize18 u-letterSpacingTight u-lineHeightTight u-marginTop7 u-textColorNormal u-baseColor--textNormal'
LINK_ARTICLE = 'col u-xs-marginBottom10 u-paddingLeft0 u-paddingRight0 u-paddingTop15 u-marginBottom30'
LINK_ARTICLE_LINK = 'u-lineHeightBase postItem'
BALISE_A = 'a'
BALISE_HREF = 'href'
DATA_ACTION = 'data-action-value'
AUTHOR_NAME = 'ui-h2 hero-title'
MEMBERSHIP = 'ui-caption u-textColorGreenNormal u-fontSize13 u-tintSpectrum u-accentColor--textNormal u-marginBottom20'
DESCRIPTION = 'ui-body hero-description'
FOLLOWERS = "button button--chromeless u-baseColor--buttonNormal is-touched"
AUTHOR_PLUS = 'buttonSet u-noWrap u-marginVertical10'
ARIA_TAG = 'aria-label'
databaseServerIP = "127.0.0.1"  # IP address of the MySQL database server
databaseUserName = "avner"  # User name of the database server
charSet = "utf8mb4"  # Character set
DB_NAME = "Toward_DataScience"  # Name of the database that is to be created
STREAM_ITEM_TAG = 'streamItem streamItem--postPreview js-streamItem'
DARKEN_TAG = 'link link--darken'
DATETIME = 'datetime'
BUTTON_TAG = 'button button--chromeless u-baseColor--buttonNormal js-multirecommendCountButton u-disablePointerEvents'
BUTTON_CHROME = 'button button--chromeless u-baseColor--buttonNormal'
